name: Deploy the react project 

on:
  push:
    branches:
      - master 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ahmedgamil/react-test -f Dockerfile.dev .
      # - run: docker run -e CI=true ahmedgamil/react-test npm run test 

  # creating a deployment package 

      - name: create deployment package
        run: zip -r deploy.zip . -x '*.git*'

  # creating the configurations of the ELASTICBEANSTALK for testing 
      - name: Deploy to elastic beanstalks 
        uses: einaregilsson/beanstalk-deploy@v20
        with: 
          aws_access_key: ${{ secrets.AWS_ACCEESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
       
          application_name: "react"
          environment_name: "React-env"
          region: "us-east-1"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip



      

